name: React Deploy

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      MY_EMAIL: davidxchelmh@gmail.com
      MY_NAME: dxchel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install Dependencies
        run: sudo apt update && sudo apt install npm && npm install
      - name: setup github access
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/dxchel/portfolio.git
          npm run deploy

