name: React Deploy

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    name: Build page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install Dependencies
        run: sudo apt update && sudo apt install npm && npm install
      - name: Build react
        run: npm run build
      - name: Add assets to build
        run: mkdir build/assets && cp src/assets/David_Xchel_Morales_Hurtado-CV.pdf build/assets
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

